### ISSUE TITLE
Please add source to New HSK data

### ISSUE THREAD

**Issue by stevendaniels** [plexus/analects-data#1]
Based on some idiosyncrasies of the new HSK data, I strongly suspect it is based on HSK lists published by Lingomi at http://lingomi.com/blog/hsk-lists-2010/

The lists are CC-by-sa.

**Comment by plexus** [comment]
Did as you asked. I really don't remember where these came from so happy to take your word for it. :)

Are you using Analects for anything, or just accidentally came across these?

**Comment by stevendaniels** [comment]
I was searching to see if cjk-decomp had been updated since version 0.4.0 and I noticed Analects. I also happen to be the creator of those new HSK lists.
